[workspace]
members = ["core", "driver"]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
strip = "symbols"

[profile.dev]
panic = "abort"
debug = 0
incremental = false

[profile.test]
debug = 0
incremental = false
