[package]
name = "babel-windows-transport"
version = "1.0.0"
edition = "2024"
license = "MIT"
rust-version = "1.90"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = ["kernel"]
kernel = []

[profile.release]
panic = "abort"
opt-level = 3
lto = "thin"
codegen-units = 1

[profile.dev]
panic = "abort"
debug = 0

[workspace]
